#ifndef MSGS_H
#define MSGS_H

#define MSG_OPEN_COM                "Opening %s at %u baud"
#define MSG_CLOSE_COM               "Closing COM port %s"

#define MSG_UPDI_INIT_OK            "UPDI init OK"
#define MSG_UPDI_INIT_NOT_OK        "UPDI not OK - reinitialisation required"
#define MSG_UPDI_INIT_FAILED        "UPDI initialization failed"

#define MSG_APPLY_RESET             "Apply reset"
#define MSG_RELEASE_RESET           "Release reset"
#define MSG_TIMEOUT_ON_UNLOCK       "Timeout by waiting for device to unlock"
#define MSG_TIMEOUT_ON_FLASH        "Waiting for flash ready timed out"
#define MSG_TIMEOUT_BEFORE_ERASE    "Timeout waiting for flash ready before erase "
#define MSG_TIMEOUT_BEFORE_BUF_CLR  "Timeout by waiting for flash ready before page buffer clear "
#define MSG_TIMEOUT_AFTER_ERASE     "Timeout by waiting for flash ready after erase"
#define MSG_TIMEOUT_AFTER_BUF_CLR   "Timeout by waiting for flash ready after page buffer clear"
#define MSG_TIMEOUT_AFTER_WRITE     "Timeout by waiting for flash ready after page write"
#define MSG_ALREADY_PROG_MODE       "Already in NVM programming mode"
#define MSG_ENTERING_PROG_MODE      "Entering NVM programming mode"
#define MSG_KEY_STATUS              "Key status = 0x%02X"
#define MSG_KEY_NOT_ACCEPTED        "Key not accepted"
#define MSG_FAIL_PROG_MODE_LOCKED   "Failed to enter NVM programming mode: device is locked"
#define MSG_FAIL_PROG_MODE          "Failed to enter NVM programming mode"
#define MSG_IN_PROG_MODE            "Now in NVM programming mode"
#define MSG_LEAVING_PROG_MODE       "Leaving NVM programming mode"
#define MSG_FAILED_TO_ERASE         "Failed to chip erase using key!"
#define MSG_WAIT_FLASH_READY        "Wait flash ready"
#define MSG_NVM_ERROR               "NVM error"
#define MSG_NVMCMD_EXEC             "NVMCMD %d executing"
#define MSG_ERASE_NVM_CTRL          "Chip erase using NVM CTRL"
#define MSG_SENDING_DBL_BREAK       "Sending double break"
#define MSG_NO_ANSWER               "No answer received"
#define MSG_INVALID_LENGTH          "Invalid length"
#define MSG_CLEAR_PAGE              "Clear page buffer"
#define MSG_COMMIT_PAGE             "Committing page"
#define MSG_READING_BYTES           "Reading %d bytes from 0x%04X"
#define MSG_CANT_READ_IN_ONE        "Cant read data in one go"
#define MSG_READING_WORDS           "Reading %d words from 0x%04X"
#define MSG_READING_PAGE            "Reading page at 0x%04X"
#define MSG_WRITING_PAGE            "Writing page at 0x%04X"

#define MSG_LDCS                    "LDCS from 0x%02X"
#define MSG_STCS                    "STCS to 0x%02X"
#define MSG_LD                      "LD from 0x%04X"
#define MSG_ST                      "ST from 0x%04X"
#define MSG_LD8_OFFSET              "LD8 from ptr++"
#define MSG_LD16_OFFSET             "LD16 from ptr++"
#define MSG_ST_TO_PTR               "ST to ptr"
#define MSG_ST8_OFFSET              "ST8 to *ptr++"
#define MSG_ST16_OFFSET             "ST16 to *ptr++"
#define MSG_REPEAT                  "Repeat %d"
#define MSG_WRITING_KEY             "Writing key"
#define MSG_INVALID_KEY_LEN         "Invalid KEY length!"

#define MSG_READING_DEVICE_INFO     "Reading device info"
#define MSG_DEVICE_ALREADY_UNLOCKED "Device already unlocked"
#define MSG_ENTER_PROG_MODE_FIRST   "Enter progmode first!"
#define MSG_FLASH_NOT_READY_FUSE    "Flash not ready for fuse setting"
#define MSG_UNABLE_ALLOC_MEM        "Unable to allocate %d bytes"
#define MSG_PROBLEM_READING_HEX     "Problem reading Hex data"
#define MSG_UNABLE_OPEN_FILE        "Unable to open file: %s"
#define MSG_READING_DEVICE_FAIL     "Reading from device failed"
#define MSG_PROBLEM_WRITING_HEX     "Problem writing Hex data"

#ifdef UPDI_CLI_mode
#define MSG_READING                 "Reading: "
#define MSG_WRITING                 "Writing: "
#endif

#endif // MSGS_H
